# NOX Version Control Sync Command

name: Synchronise NOX definition with version control

cli:
  branch: sync
  command: version-control
  command-alias: vc
  description: "|vc - Sets up or synchronizes a repository on Azure Devops for your NOX team."
  examples:
    - ["sync versionControl", "--path <designFolder>"]
    - ["sync vc", "--path <designFolder>"]

jobs:
  main-setup:
    steps:
      - name: Get Project dash case name
        id: get-project-dash-name
        uses: core/to-dash-case@v1
        with:
          source-string: ${{ project.versionControl.project }}
        display:
          success: Got the Project dash case name
          error: Unable to get the Project dash case name (${{ steps.get-project-dash-name.error-message }})

      - name: Get the project snake case name
        id: get-project-snake-name
        uses: core/to-snake-case@v1
        with:
          source-string: ${{ project.versionControl.project }}
        display:
          success: Got the Project snake case name
          error: Unable to get the Project snake case name (${{ steps.get-project-snake-name.error-message }})
          
      - name: Get the Team Member user name list
        id: get-team-uname-list
        uses: project/get-team-user-names@v1
        with:
          team-members: ${{ project.team.developers }}
        display:
          success: Got the team user name list
          error: Unable to get the team user name list (${{ steps.get-team-uname-list.error-message }})

      - name: Get the Team Admins user name list
        id: get-project-admin-uname-list
        uses: project/get-admin-user-names@v1
        with:
          team-members: ${{ project.team.developers }}
        display:
          success: Got the project admins user name list
          error: Unable to get the project admins user name list (${{ steps.get-project-admin-list.error-message }})

      - name: Store setup variables
        id: add-setup-vars
        uses: core/add-variables@v1
        with:
          project-name: ${{ project.versionControl.project }}
          project-dash-name: ${{ steps.get-project-dash-name.outputs.result }}
          project-snake-name: ${{ steps.get-project-snake-name.outputs.result }}
          team-user-names: ${{ steps.get-team-uname-list.outputs.user-names }}
          admin-user-names: ${{ steps.get-project-admin-uname-list.outputs.user-names }}
        display:
          success: Variables stored
          error: Unable to store project variables ${{ steps.add-setup-vars.error-message }}
          
  connect:
    steps:
      - name: Locate the DevOps server
        id: locate-devops
        uses: network/ping@v1
        with:
          host: ${{ project.versionControl.server }}
        display:
          success: Found the DevOps server in ${{ steps.locate-devops.outputs.roundtrip-time }} milliseconds
          error: The DevOps server is not accessible. Are you connected to the Internet?
        run-at-server: true

      - name: Connect to the DevOps server
        id: connect-devops
        uses: azdevops/connect@v1
        with:
          server: ${{ project.versionControl.server }}
          personal-access-token: ${{ server.secrets.AZURE_DEVOPS_PAT }}
        display:
          success: Connected to the DevOps server
          error: There was a problem connecting to the DevOps server. (${{ steps.connect-devops.error-message }})
        run-at-server: true
          
  sync-version-control:
    $ref: SyncVersionControl.steps.nox.yaml