version: 2
updates:
  - package-ecosystem: nuget
    directory: /src
    schedule:
      interval: daily
      time: "08:00"
    groups:
      deps:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
