# NOX Elastic APM Alerts Sync Command

name: Synchronise NOX definition with Elastic APM Alerts

cli:
  branch: sync
  command: elastic-apm-alerts
  command-alias: apm
  description: "|ea - Creates or updates your Elastic APM alerts with NOX definition."
  examples:
    - ["sync elastic-apm-alerts", "--path <designFolder>"]
    - ["sync apm", "--path <designFolder>"]

jobs:
  sync-elastic-apm:  
    steps:

      - name: Locate the DevOps server
        id: locate-server
        uses: network/ping@v1
        with:
          host: ${{ project.versionControl.server }}
        display:
          success: Found the DevOps server in ${{ steps.locate-server.outputs.roundtrip-time }} milliseconds
          error: The DevOps server is not accesable. Are you connected to the Internet? 
        run-at-server: true

      - name: Connect to the DevOps server
        id: connect-server
        uses: azdevops/connect@v1
        with:
          server: ${{ project.versionControl.server }}
          personal-access-token: ${{ server.secrets.AZURE_DEVOPS_PAT }}
        display:
          success: Connected to the DevOps server
          error: There was a problem connecting to the DevOps server. (${{ steps.connect-server.error-message }})
        run-at-server: true

      - name: Get the Nox Team project
        id: get-nox-project
        uses: azdevops/get-project@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-name: ${{ project.versionControl.project }}
        display:
          success: Got the ${{ project.versionControl.project }} DevOps project
          error: There was a problem getting the ${{ project.versionControl.project }} project. (${{ steps.get-nox-project.error-message }})
        run-at-server: true

      - name: Ensure the Project APM Repository exists
        id: ensure-nox-apm-repo
        uses: azdevops/ensure-repo-exists@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-id: ${{ steps.get-nox-project.outputs.project-id }}
          repository-name: elastic-alert-config
        display:
          success: Ensured that the project elastic-alert-config repository exists
          error: There was a problem ensuring that the project elastic-alert-config repository exists. ${{ steps.ensure-nox-apm-repo.error-message }}
        run-at-server: true

      - name: Get the IWG.APM project
        id: get-apm-project
        if: '"${{ steps.ensure-nox-apm-repo.outputs.is-found }}" == "False"'
        uses: azdevops/get-project@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-name: IWG.APM
        display:
          success: Got the IWG.APM project
          error: There was a problem getting the IWG.APM project (${{ steps.get-apm-project.error-message }})
        run-at-server: true

      - name: Get the APM alert config repo
        id: get-apm-alert-repo
        if: '"${{ steps.ensure-nox-apm-repo.outputs.is-found }}" == "False"'
        uses: azdevops/get-repo@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-id: ${{ steps.get-apm-project.outputs.project-id }}
          repository-name: elastic-alert-config
        display:
          success: Successfully got the APM alert config repo
          error: There was a problem getting the APM alert config repository (${{ steps.get-apm-alert-repo.error-message }})
        run-at-server: true

      - name: Download the APM alert config repo
        id: download-apm-repo
        if: '"${{ steps.ensure-nox-apm-repo.outputs.is-found }}" == "False"'
        uses: azdevops/download-repo-branch@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.get-apm-alert-repo.outputs.repository-id }}
          branch-name: main
        display:
          success: Successfully downloaded branch 'main' of the APM alert config repo to ${{ steps.download-apm-repo.outputs.local-repository-path }}
          error: There was a problem downloading the repository (${{ steps.download-apm-repo.error-message }})
        run-at-server: true

      - name: Push APM repo to project main branch
        id: push-apm-repo-to-main
        if: '"${{ steps.ensure-nox-apm-repo.outputs.is-found }}" == "False"'
        uses: azdevops/push-folder@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.ensure-nox-apm-repo.outputs.repository-id }}
          source-path: ${{ steps.download-apm-repo.outputs.local-repository-path }}
        display:
          success: Push elastic-alert-config to project ${{ project.name }} success
          error: Push elastic-alert-config to project ${{ project.name }} failed. (${{ steps.push-apm-repo-to-main.error-message }})
        run-at-server: true

      - name: Create new APM alerts branch
        id: create-new-apm-branch
        uses: azdevops/create-branch@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.ensure-nox-apm-repo.outputs.repository-id }}
        display:
          success: Successfully created new APM alerts branch -> ${{ steps.create-new-apm-branch.outputs.branch-name }}
          error: Failed to create new APM alerts branch -> ${{ steps.create-new-apm-branch.outputs.branch-name }}
        run-at-server: true

      - name: Download the new APM alerts branch
        id: download-apm-branch
        uses: azdevops/download-repo-branch@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.ensure-nox-apm-repo.outputs.repository-id }}
          branch-name: ${{ steps.create-new-apm-branch.outputs.branch-name }}
        display:
          success: Successfully downloaded branch '${{ steps.create-new-apm-branch.outputs.branch-name }}' of the project APM alert config repo to ${{ steps.download-project-apm-repo.outputs.local-repository-path }}
          error: There was a problem downloading the project APM config repository (${{ steps.download-project-apm-repo.error-message }})
        run-at-server: true

      - name: Get team email address list
        id: get-team-email-list
        uses: core/concatenate-list-property@v1
        with:
          source-list: ${{ project.team.developers }}
          property-name: Email
        display:
          success: Successfully created support email address list
          error: There was a problem creating the support email address list (${{ steps.get-team-email-list.error-message }})


# Replace apm_anomaly_detected.json
      - name: apm_anomaly_detected Replace
        id: replace-anomaly
        uses: file/replace-strings@v1
        with:
          path: ${{ steps.download-project-apm-repo.outputs.local-repository-path }}/apm_anomaly_detected.json
          replacements:
            "<service_name>": ${{ project.versionControl.project }},
            "<environment>": ${{ env.ASPNETCORE_ENVIRONMENT }},
            "<support_email_address>": ${{ steps.get-team-email-list.outputs.result }}
        display:
          success: Strings successfully Replaced in anomaly alert
          error: Strings Replace in anomaly alert failed. (${{ steps.replace-anomaly.error-message }})
        run-at-server: true

# Replace apm_high_error_rate.json
      - name: apm_high_error_rate Replace
        id: replace-high-error
        uses: file/replace-strings@v1
        with:
          path: ${{ steps.download-project-apm-repo.outputs.local-repository-path }}/apm_high_error_rate.json
          replacements:
            "<service_name>": ${{ project.versionControl.project }},
            "<environment>": ${{ env.ASPNETCORE_ENVIRONMENT }},
            "<support_email_address>": ${{ steps.get-team-email-list.outputs.result }}
        display:
          success: Strings successfully Replaced in high error rate alert
          error: Strings Replace high error rate alert failed. (${{ steps.replace-high-error.error-message }})
        run-at-server: true

# Replace apm_high_p95_response_time.json
      - name: apm_high_p95_response_time Replace
        id: replace-p95
        uses: file/replace-strings@v1
        with:
          path: ${{ steps.download-project-apm-repo.outputs.local-repository-path }}/apm_high_p95_response_time.json
          replacements:
            "<service_name>": ${{ project.versionControl.project }},
            "<environment>": ${{ env.ASPNETCORE_ENVIRONMENT }},
            "<support_email_address>": ${{ steps.get-team-email-list.outputs.result }}
        display:
          success: Strings successfully Replaced in p95 alert
          error: Strings Replace p95 alert failed. (${{ steps.replace-p95.error-message }})
        run-at-server: true

      - name: Push updated apm branch to project apm repo
        id: merge-apm-repo
        uses: azdevops/merge-folder@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.ensure-nox-apm-repo.outputs.repository-id }}
          source-path: ${{ steps.download-project-apm-repo.outputs.local-repository-path }}
        display:
          success: Push updated elastic-alert-config to project ${{ project.name }} success
          error: Push updated elastic-alert-config to project ${{ project.name }} failed. (${{ steps.merge-apm-repo.error-message }})
        run-at-server: true
