# NOX New Service Command

name: Creates a new NOX service

cli:
  branch: new
  command: service
  description: Creates a new NOX service
  examples:
    - ["new service", "--path <designFolder>"]

jobs:
  new-service:
    steps:
      - name: Create a new service definition
        id: add-new-service
        uses: yamlmaker/build@v1 # user input 
        with:
          schema-url: https://noxorg.dev/schemas/NoxConfiguration.json ## hard code yaml?
          output-path: ./src/${{ config.Name }}/Design   ## optional, json/yaml
          prompt-for: all ## include or exclude fields
