# NOX Heimdall Helm Chart Sync Command

name: Synchronise NOX definition with Heimdall Helm Chart

cli:
  branch: sync
  command: helm-chart
  command-alias: hc
  description: Synchronises NOX definition with Heimdall Helm Chart.
  examples:
    - ["sync helm-chart", "--path <designFolder>"]
    - ["sync hc", "--path <designFolder>"]

jobs:
  sync-heimdall-helm-chart:  
    steps:

      - name: Locate the DevOps server
        id: locate-server
        uses: network/ping@v1
        with:
          host: ${{ config.versionControl.server }}
        display:
          success: Found the DevOps server in ${{ steps.locate-server.outputs.roundtrip-time }} milliseconds
          error: The DevOps server is not accesable. Are you connected to the Internet? 

      - name: Connect to the DevOps server
        id: connect-server
        uses: azdevops/connect@v1
        with:
          server: ${{ config.versionControl.server }}
          personal-access-token: ${{ secrets.AZURE_DEVOPS_PAT }}
        display:
          success: Connected to the DevOps server
          error: There was a problem connecting to the DevOps server. (${{ steps.connect-server.error-message }})

      - name: Get the Team project
        id: get-project
        uses: azdevops/get-project@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-name: ${{ config.versionControl.project }}
        display:
          success: Got the DevOps project
          error: There was a problem getting the project (${{ steps.ensure-project.error-message }})

      - name: Create the Repository
        id: ensure-repo
        uses: azdevops/ensure-repo@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-name: ${{ config.versionControl.project }}
          repository-name: ${{ config.versionControl.repository }}
        display:
          success: Created the DevOps repository
          error: There was a problem creating the repository (${{ steps.ensure-repo.error-message }})
          
      - name: Add team members to the project
        id: add-team-members
        uses: azdevops/add-team-members@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-name: ${{ config.versionControl.project }}
          team-members: ${{ config.team.developers }}
        display:
          success: Added team members to the DevOps project
          error: There was a problem adding team members to the project (${{ steps.ensure-repo.error-message }})          
