# NOX Azure Active Directory Sync Command

name: Synchronise NOX definition with Azure Active Directory

cli:
  branch: sync
  command: azure-active-directory
  command-alias: ad
  description: "|ad - Synchronises NOX team definition with your Azure Active Directory (AAD)."
  examples:
    - ["sync azure-active-directory", "--path <designFolder>"]
    - ["sync azad", "--path <designFolder>"]
    
jobs:
  sync-directory-service:
    steps:

      - name: Connect to Azure Active Directory
        id: connect
        uses: azuread/connect@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        display:
          success: Successfully connected to Azure Active Directory
          error: Unable to connect to Azure Active Directory
        run-at-server: true
          
      - name: Create the project AAD group
        id: create-project-group
        uses: azuread/create-group@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          group-name: NOX_PROJECT_${{ project.name }}
          group-description: ${{ project.description }}
        display:
          success: Created the Project AAD group
          error: Unable to create the Project AAD group
        run-at-server: true
          
      - name: Create an AAD security group
        id: create-security-group
        uses: azuread/create-group@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          group-name: NOX_PROJECTS_ALL
          group-description: Nox Projects - Security Group
        display:
          success: Created the AAD security group
          error: Unable to create the AAD security group
        run-at-server: true
          
      - name: Add project group as a member of security group
        id: add-project-group-to-security-group
        uses: azuread/add-group-to-group@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          child-group: ${{ steps.create-project-group.outputs.group-id }}
          parent-group: ${{ steps.create-security-group.outputs.group-id }}
        display:
          success: Added the project group to the security group
          error: Unable to add the project group to the security group
        run-at-server: true
      
      - name: Create an MS teams, team for the project
        id: create-ms-team
        uses: teams/create-team@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          aad-group-id: ${{ steps.create-project-group.outputs.group-id }}
          team-name: ${{ project.name }}_Team
          team-description: Team for members of the ${{ project.name }} project
        display:
          success: Created an MS Teams, team for the project
          error: Unable to create an MS Teams, team for the project ($${{ steps.create-ms-team.error-message }})
        run-at-server: true
      
      - name: Get the Team Member user name list
        id: get-team-uname-list
        uses: project/get-team-user-names
        with:
          team-members: ${{ project.team.developers }}
        display:
          success: Got the team user name list
          error: Unable to get the team user name list (${{ steps.get-team-uname-list.error-message }})

      - name: Get Team member user object Id list
        id: get-team-obj-id-list
        uses: azuread/get-users-object-id-list@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          user-names: ${{ steps.get-team-uname-list.outputs.team-user-names }}
        display:
          success: Got the Team members object ids
          error: Unable to get the team members object ids (${{ steps.get-team-obj-id-list.error-message }})
        run-at-server: true

      - name: Get the Team Admins user name list
        id: get-team-admin-uname-list
        uses: project/get-team-admin-user-names
        with:
          team-members: ${{ project.team.developers }}
        display:
          success: Got the team admins user name list
          error: Unable to get the team admins user name list (${{ steps.get-team-admin-list.error-message }})

      - name: Get the team admins user object Id list
        id: get-team-admin-obj-id-list
        uses: azuread/get-users-object-id-list@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          user-names: ${{ steps.get-team-admin-uname-list.outputs.team-user-names }}
        display:
          success: Got the Team admins object ids
          error: Unable to get the team admins object ids (${{ steps.get-team-admin-obj-id-list.error-message }})
        run-at-server: true
      
      - name: Add project team members to project group
        id: add-members-to-aad-group
        uses: azuread/add-users-to-group@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          group-id: ${{ steps.create-project-group.outputs.group-id }}
          user-object-ids: ${{ steps.get-team-obj-id-list.outputs.object-ids }}
        display:
          success: Added project team members to project group
          error: Unable to add project team members to project group (${{ steps.add-members-to-aad-group.error-message }})
        run-at-server: true

      - name: Add project admins to project group
        id: add-admins-to-aad-group
        uses: azuread/add-users-to-group@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          group-id: ${{ steps.create-project-group.outputs.group-id }}
          user-object-ids: ${{ steps.get-team-obj-id-list.outputs.object-ids }}
          is-owner: true
        display:
          success: Added project team admins to project AAD group
          error: Unable to add project admins to project AAD group (${{ steps.add-admins-to-aad-group.error-message }})
        run-at-server: true

      - name: Add Project team members to MS Team
        id: add-members-to-ms-team
        uses: teams/add-members@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          user-object-ids: ${{ steps.get-team-obj-id-list.outputs.object-ids }}
        display:
          success: Added team members to MS Teams, team
          error: Unable to add team members to MS Teams, team (${{ steps.add-members-to-ms-team.error-message }})
        run-at-server: true

      - name: Add Project Admins to MS Team
        id: add-admins-to-ms-team
        uses: teams/add-members@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          user-object-ids: ${{ steps.get-admin-obj-id-list.outputs.object-ids }}
          is-owner: true
        display:
          success: Added team admins to MS Teams, team
          error: Unable to add team admins to MS Teams, team (${{ steps.add-admins-to-ms-team.error-message }})
        run-at-server: true

      - name: Add DevOps group to MS Team
        id: add-devops-to-ms-team
        uses: teams/add-member@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          user-object-id: e00e4ac2-4318-472b-8c78-8cd8c3a54685
          is-owner: true
        display:
          success: Added DevOps to MS Teams, team
          error: Unable to add DevOps to MS Teams, team (${{ steps.add-devops-to-ms-team.error-message }})
        run-at-server: true
