# NOX Version Control Sync Command

name: Synchronise NOX project definition with Terraform Infrastructure

cli:
  branch: sync
  command: infrastructure
  command-alias: iac
  description: "|iac - Sets up or synchronizes the infrastructure repos on Azure Devops for your NOX project."
  examples:
    - ["sync infrastructure", "--path <designFolder>"]
    - ["sync iac", "--path <designFolder>"]

jobs:
  sync-infrastructure:  
    steps:

      - name: Locate the DevOps server
        id: locate-server
        uses: network/ping@v1
        with:
          host: ${{ project.versionControl.server }}
        display:
          success: Found the DevOps server in ${{ steps.locate-server.outputs.roundtrip-time }} milliseconds
          error: The DevOps server is not accesable. Are you connected to the Internet?
        run-at-server: true

      - name: Connect to the DevOps server
        id: connect-server
        uses: azdevops/connect@v1
        with:
          server: ${{ project.versionControl.server }}
          personal-access-token: ${{ server.secrets.AZURE_DEVOPS_PAT }}
        display:
          success: Connected to the DevOps server
          error: There was a problem connecting to the DevOps server. (${{ steps.connect-server.error-message }})
        run-at-server: true

      - name: Get the Nox Team project
        id: get-nox-project
        uses: azdevops/get-project@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-name: ${{ project.versionControl.project }}
        display:
          success: Got the ${{ project.versionControl.project }} DevOps project
          error: There was a problem getting the ${{ project.versionControl.project }} project. (${{ steps.get-nox-project.error-message }})
        run-at-server: true

      - name: Ensure the Project infrastructure Repository exists
        id: ensure-terraform-repo
        uses: azdevops/ensure-repo-exists@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-id: ${{ steps.get-nox-project.outputs.project-id }}
          repository-name: ${{ project.versionControl.project }}-infrastructure-tf
        display:
          success: Ensured that the project infrastructure repository exists
          error: There was a problem ensuring that the project infrastructure repository exists. ${{ steps.ensure-terraform-repo.error-message }}
        run-at-server: true

      - name: Find the project infra repo main branch
        id: find-main
        uses: azdevops/find-branch@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.ensure-terraform-repo.outputs.repository-id }}
          branch-name: main
        display:
          success: Sucessfully got the main branch
          error: There was a problem getting the main branch for the project infrastructure repo
        run-at-server: true

#if the project infra repo does not exist the create it
      - name: Get the Heimdall project
        id: get-heimdall-project
        if: '"${{ steps.find-main.outputs.is-found }}" == "False"'
        uses: azdevops/get-project@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-name: Heimdall.Microservices
        display:
          success: Got the Heimdall.Microservices project
          error: There was a problem getting the Heimdall.Microservices project (${{ steps.get-heimdall-project.error-message }})
        run-at-server: true

      - name: Get the Heimdall infra repo
        id: get-heimdall-terraform-repo
        if: '"${{ steps.find-main.outputs.is-found }}" == "False"'
        uses: azdevops/get-repo@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-id: ${{ steps.get-heimdall-project.outputs.project-id }}
          repository-name: Product-infrastructure-tf
        display:
          success: Successfully got the Heimdall terraform repo
          error: There was a problem getting the Heimdall terraform repository (${{ steps.get-heimdall-terraform-repo.error-message }})
        run-at-server: true

      - name: Download the heimdall terraform repo
        id: download-terraform-repo
        if: '"${{ steps.find-main.outputs.is-found }}" == "False"'
        uses: azdevops/download-repo-branch@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.get-heimdall-terraform-repo.outputs.repository-id }}
          branch-name: main
        display:
          success: Successfully downloaded branch 'main' of the Heimdall terraform repo to ${{ steps.download-terraform-repo.outputs.local-repository-path }}
          error: There was a problem downloading the Heimdall terraform repository (${{ steps.download-terraform-repo.error-message }})
        run-at-server: true

      - name: Push the terraform repo to project main branch
        id: push-terraform-repo-to-main
        if: '"${{ steps.find-main.outputs.is-found }}" == "False"'
        uses: azdevops/push-folder@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.ensure-terraform-repo.outputs.repository-id }}
          source-path: ${{ steps.download-terraform-repo.outputs.local-repository-path }}
        display:
          success: Push the terraform repo to project ${{ project.name }} success
          error: Push the terraform repo to project ${{ project.name }} failed. (${{ steps.push-terraform-repo-to-main.error-message }})
        run-at-server: true

      - name: Create a new terraform branch
        id: create-new-terraform-branch
        uses: azdevops/create-branch@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.ensure-terraform-repo.outputs.repository-id }}
        display:
          success: Successfully created new terraform branch -> ${{ steps.create-new-terraform-branch.outputs.branch-name }}
          error: Failed to create new terraform branch -> ${{ steps.create-new-terraform-branch.outputs.branch-name }}
        run-at-server: true

      - name: Download the new terraform branch
        id: download-terraform-branch
        uses: azdevops/download-repo-branch@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.ensure-terraform-repo.outputs.repository-id }}
          branch-name: ${{ steps.create-new-terraform-branch.outputs.branch-name }}
        display:
          success: Successfully downloaded branch '${{ steps.create-new-terraform-branch.outputs.branch-name }}' of the repo to ${{ steps.download-terraform-branch.outputs.local-repository-path }}
          error: There was a problem downloading the project helm-chart branch (${{ steps.download-terraform-branch.error-message }})
        run-at-server: true

# Replace variables.tf
      - name: variables.tf Replace
        id: replace-variables-tf
        uses: file/replace-strings@v1
        with:
          path: ${{ steps.download-terraform-branch.outputs.local-repository-path }}/variables.tf
          replacements:
            "default     = \"prd\"": "default     = \"Nox\""
            "default     = \"product\"": "default     = \"${{ project.versionControl.project }}\""
        display:
          success: Strings Replace in variables.tf success
          error: Strings Replace in variables.tf failed. (${{ steps.replace-variables-tf.error-message }})
        run-at-server: true

      - name: Push updated terraform branch to project helm-chart repo
        id: merge-terraform-repo
        uses: azdevops/merge-folder@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.ensure-terraform-repo.outputs.repository-id }}
          branch-name: ${{ steps.create-new-terraform-branch.outputs.branch-name }}
          source-path: ${{ steps.download-terraform-branch.outputs.local-repository-path }}
        display:
          success: Push updated terraform branch to project ${{ project.name }} success
          error: Push updated terraform branch to project ${{ project.name }} failed. (${{ steps.merge-terraform-repo.error-message }})
        run-at-server: true

# tfe section
      - name: Get the Terraform project
        id: get-terraform-project
        uses: azdevops/get-project@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-name: Terraform
        display:
          success: Got the Terraform project
          error: There was a problem getting the Terraform project (${{ steps.get-heimdall-project.error-message }})
        run-at-server: true

      - name: Get the Terraform tfe-manage-workspaces repo
        id: get-terraform-tfe-manage-workspaces-repo
        uses: azdevops/get-repo@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-id: ${{ steps.get-terraform-project.outputs.project-id }}
          repository-name: tfe-manage-workspaces
        display:
          success: Successfully got the Terraform tfe-manage-workspaces repo
          error: There was a problem getting the Terraform tfe-manage-workspacesrepository (${{ steps.get-terraform-tfe-manage-workspaces-repo.error-message }})
        run-at-server: true

      - name: Create a new tfe-manage-workspaces branch
        id: create-new-tfe-manage-workspaces-branch
        uses: azdevops/create-branch@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.get-terraform-tfe-manage-workspaces-repo.outputs.repository-id }}
        display:
          success: Successfully created new tfe-manage-workspaces branch -> ${{ steps.create-new-tfe-manage-workspaces-branch.outputs.branch-name }}
          error: Failed to create new tfe-manage-workspaces branch -> ${{ steps.create-new-tfe-manage-workspaces-branch.outputs.branch-name }}
        run-at-server: true

      - name: Download the new tfe-manage-workspaces branch
        id: download-tfe-manage-workspaces-branch
        uses: azdevops/download-repo-branch@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          repository-id: ${{ steps.get-terraform-tfe-manage-workspaces-repo.outputs.repository-id }}
          branch-name: ${{ steps.create-new-tfe-manage-workspaces-branch.outputs.branch-name }}
        display:
          success: Successfully downloaded branch '${{ steps.create-new-tfe-manage-workspaces-branch.outputs.branch-name }}' of the repo to ${{ steps.download-tfe-manage-workspaces-branch.outputs.local-repository-path }}
          error: There was a problem downloading the tfe-manage-workspaces branch (${{ steps.download-tfe-manage-workspaces-branch.error-message }})
        run-at-server: true