# NOX Version Control Sync Command

name: Synchronise NOX definition with version control

cli:
  branch: sync
  command: version-control
  command-alias: vc
  description: Synchronises NOX team definition with your version control service.
  examples:
    - ["sync versionControl", "--path <designFolder>"]
    - ["sync vc", "--path <designFolder>"]

jobs:
  sync-versionControl:  
    steps:

      - name: Locate the DevOps server
        id: locate-server
        uses: network/ping@v1
        with:
          host: ${{ config.versionControl.server }}
        display:
          success: Found the DevOps server in ${{ steps.locate-server.outputs.roundtrip-time }} milliseconds
          error: The DevOps server is not accesable. Are you connected to the Internet? 

      - name: Connect to the DevOps server
        id: connect-server
        uses: azdevops/connect@v1
        with:
          server: ${{ config.versionControl.server }}
          personal-access-token: ${{ secrets.AZURE_DEVOPS_PAT }}
        display:
          success: Connected to the DevOps server
          error: There was a problem connecting to the DevOps server. (${{ steps.connect-server.error-message }})

      - name: Ensure the Team project exists
        id: ensure-project
        uses: azdevops/ensure-project@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-name: ${{ config.versionControl.project }}
          project-description: ${{ config.description }}
        display:
          success: Created the DevOps project
          error: There was a problem creating the project (${{ steps.ensure-project.error-message }})

      - name: Add team members to the project
        id: add-team-members
        uses: azdevops/add-team-members@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-name: ${{ config.versionControl.project }}
          team-members: ${{ config.team.developers }}
        display:
          success: Added team members to the DevOps project
          error: There was a problem adding team members to the project (${{ steps.ensure-repo.error-message }})           

      - name: Ensure the Repository exists
        id: ensure-repo
        uses: azdevops/ensure-repo@v1
        with:
          connection: ${{ steps.connect-server.outputs.connection }}
          project-id: ${{ steps.ensure-project.outputs.project-id }}
          repository-name: ${{ config.versionControl.repository }}
        display:
          success: Ensured that the DevOps repository exists
          error: There was a problem ensuring that the repository exists. (${{ steps.ensure-repo.error-message }})

