# NOX Azure Active Directory Sync Command

name: Synchronise NOX definition with Azure Active Directory

cli:
  branch: sync
  command: azure-active-directory
  command-alias: ad
  description: "|ad - Synchronises NOX team definition with your Azure Active Directory (AAD)."
  examples:
    - ["sync azure-active-directory", "--path <designFolder>"]
    - ["sync azad", "--path <designFolder>"]
    
jobs:
  sync-directory-service:
    steps:

      - name: Connect to Azure Active Directory
        id: connect
        uses: azuread/connect@v1
        with:
          tenant-id: ${{ server.secrets.AZURE_TENANT_ID }}
          client-id: ${{ server.secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ server.secrets.AZURE_CLIENT_SECRET }}
        display:
          success: Successfully connected to Azure Active Directory
          error: Unable to connect to Azure Active Directory
        run-at-server: true
          
      - name: Create the project AAD group
        id: create-project-group
        uses: azuread/create-group@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          group-name: NOX_PROJECT_${{ project.name }}
          group-description: ${{ project.description }}
        display:
          success: Created the Project AAD group
          error: Unable to create the Project AAD group (${{ steps.create-project-group.error-message }})
        run-at-server: true
          
      - name: Create an AAD security group
        id: create-security-group
        uses: azuread/create-group@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          group-name: NOX_PROJECTS_ALL
          group-description: Nox Projects - Security Group
        display:
          success: Created the AAD security group
          error: Unable to create the AAD security group (${{ steps.create-security-group.error-message }})
        run-at-server: true
          
      - name: Add project group as a member of security group
        id: add-project-group-to-security-group
        uses: azuread/add-group-to-group@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          child-group-id: ${{ steps.create-project-group.outputs.group-id }}
          parent-group-id: ${{ steps.create-security-group.outputs.group-id }}
        display:
          success: Added the project group to the security group
          error: Unable to add the project group to the security group (${{ steps.add-project-group-to-security-group.error-message }})
        run-at-server: true
      
      - name: Create an MS teams, team for the project
        id: create-ms-team
        uses: teams/create-team@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          aad-group-id: ${{ steps.create-project-group.outputs.group-id }}
          team-name: ${{ project.name }}_Team
          team-description: Team for members of the ${{ project.name }} project
        display:
          success: Created an MS Teams, team for the project
          error: Unable to create an MS Teams, team for the project ($${{ steps.create-ms-team.error-message }})
        run-at-server: true
      
      - name: Get the Team Member user name list
        id: get-team-uname-list
        uses: project/get-team-user-names@v1
        with:
          team-members: ${{ project.team.developers }}
        display:
          success: Got the team user name list
          error: Unable to get the team user name list (${{ steps.get-team-uname-list.error-message }})

      - name: Get Team member user object Id list
        id: get-team-obj-id-list
        uses: azuread/get-users-object-id-list@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          user-names: ${{ steps.get-team-uname-list.outputs.team-user-names }}
        display:
          success: Got the Team members object ids
          error: Unable to get the team members object ids (${{ steps.get-team-obj-id-list.error-message }})
        run-at-server: true

      - name: Get the Team Admins user name list
        id: get-project-admin-uname-list
        uses: project/get-admin-user-names@v1
        with:
          team-members: ${{ project.team.developers }}
        display:
          success: Got the project admins user name list
          error: Unable to get the project admins user name list (${{ steps.get-project-admin-list.error-message }})

      - name: Get the team admins user object Id list
        id: get-team-admin-obj-id-list
        uses: azuread/get-users-object-id-list@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          user-names: ${{ steps.get-team-admin-uname-list.outputs.team-user-names }}
        display:
          success: Got the Team admins object ids
          error: Unable to get the team admins object ids (${{ steps.get-team-admin-obj-id-list.error-message }})
        run-at-server: true
      
      - name: Add project team members to project group
        id: add-members-to-aad-group
        uses: azuread/add-users-to-group@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          group-id: ${{ steps.create-project-group.outputs.group-id }}
          user-object-ids: ${{ steps.get-team-obj-id-list.outputs.object-ids }}
        display:
          success: Added project team members to project group
          error: Unable to add project team members to project group (${{ steps.add-members-to-aad-group.error-message }})
        run-at-server: true

      - name: Add project admins to project group
        id: add-admins-to-aad-group
        uses: azuread/add-users-to-group@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          group-id: ${{ steps.create-project-group.outputs.group-id }}
          user-object-ids: ${{ steps.get-team-obj-id-list.outputs.object-ids }}
          is-owner: true
        display:
          success: Added project team admins to project AAD group
          error: Unable to add project admins to project AAD group (${{ steps.add-admins-to-aad-group.error-message }})
        run-at-server: true

      - name: Add Nox.Cli to project group
        id: add-cli-to-project-group
        uses: azuread/add-user-to-group@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          group-id: ${{ steps.create-project-group.outputs.group-id }}
          user-object-id: 081ed5f0-1bdf-406a-a2c5-b4f7341bf3ee
          is-owner: true
        display:
          success: Added Nox.Cli to project AAD group
          error: Unable to add Nox.Cli to project AAD group (${{ steps.add-cli-to-project-group.error-message }})
        run-at-server: true

      - name: Add Project team members to MS Team
        id: add-members-to-ms-team
        uses: teams/add-members@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          user-object-ids: ${{ steps.get-team-obj-id-list.outputs.object-ids }}
        display:
          success: Added team members to MS Teams, team
          error: Unable to add team members to MS Teams, team (${{ steps.add-members-to-ms-team.error-message }})
        run-at-server: true

      - name: Add Project Admins to MS Team
        id: add-admins-to-ms-team
        uses: teams/add-members@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          user-object-ids: ${{ steps.get-admin-obj-id-list.outputs.object-ids }}
          is-owner: true
        display:
          success: Added team admins to MS Teams, team
          error: Unable to add team admins to MS Teams, team (${{ steps.add-admins-to-ms-team.error-message }})
        run-at-server: true

      - name: Add Nox.Cli to MS Team
        id: add-cli-to-ms-team
        uses: teams/add-member@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          user-object-id: 081ed5f0-1bdf-406a-a2c5-b4f7341bf3ee
          is-owner: true
        display:
          success: Added Nox.Cli to MS Teams, team
          error: Unable to add Nox.Cli to MS Teams, team (${{ steps.add-cli-to-ms-team.error-message }})
        run-at-server: true

      - name: Add DevOps group to MS Team
        id: add-devops-to-ms-team
        uses: teams/add-member@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          user-object-id: e00e4ac2-4318-472b-8c78-8cd8c3a54685
          is-owner: true
        display:
          success: Added DevOps to MS Teams, team
          error: Unable to add DevOps to MS Teams, team (${{ steps.add-devops-to-ms-team.error-message }})
        run-at-server: true

      - name: Create a channel on the MS Team
        id: create-cli-channel
        uses: teams/create-channel@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          channel-name: Nox Cli message channel
          channel-description: Channel used by Nox.Cli to message members of the project team
        display:
          success: Created the Cli channel on the MS Teams team
          error: Unable to create the Cli channel on the MS Teams team (${{ steps.create-cli-channel.error-message }})
        run-at-server: true

      - name: Add Nox.Cli to channel
        id: add-cli-to-channel
        uses: teams/add-channel-member@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          channel-id: ${{ steps.create-cli-channel.outputs.channel-id }}
          object-id: 081ed5f0-1bdf-406a-a2c5-b4f7341bf3ee
          is-owner: true
        display:
          success: Added Nox.Cli to the project team channel
          error: Unable to add Nox.Cli to the project team channel (${{ steps.add-cli-to-channel.error-message }})
        run-at-server: true

      - name: Add team members to channel
        id: add-team-to-channel
        uses: teams/add-channel-members@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          channel-id: ${{ steps.create-cli-channel.outputs.channel-id }}
          object-ids: ${{ steps.get-team-obj-id-list.outputs.object-ids }}
        display:
          success: Added project members to the project team channel
          error: Unable to add project members to the project team channel (${{ steps.add-team-to-channel.error-message }})
        run-at-server: true

      - name: Add admins to channel
        id: add-admins-to-channel
        uses: teams/add-channel-members@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          channel-id: ${{ steps.create-cli-channel.outputs.channel-id }}
          object-ids: ${{ steps.get-admin-obj-id-list.outputs.object-ids }}
          is-owner: true
        display:
          success: Added project admins to the project team channel
          error: Unable to add project admins to the project team channel (${{ steps.add-admins-to-channel.error-message }})
        run-at-server: true

      - name: Send Test message on project channel
        id: send-project-test-message
        uses: teams/send-channel-message@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          channel-id: ${{ steps.create-cli-channel.outputs.channel-id }}
          message-body: Welcome to the ${{ project.name }} project team!
        display:
          success: Sent a test message to the project team channel
          error: Unable to send a test message to the project team channel (${{ steps.send-project-test-message.error-message }})
        run-at-server: true

      - name: Create a DevOps channel on the MS Team
        id: create-devops-channel
        uses: teams/create-channel@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          channel-name: ${{ project.name }} - DevOps channel
          channel-description: Channel used by Nox.Cli to message DevOps members.
        display:
          success: Created the DevOps channel on the MS Teams team
          error: Unable to create the DevOps channel on the MS Teams team (${{ steps.create-devops-channel.error-message }})
        run-at-server: true

      - name: Add Nox.Cli toDevOps channel
        id: add-cli-to-devops-channel
        uses: teams/add-channel-member@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          channel-id: ${{ steps.create-devops-channel.outputs.channel-id }}
          object-id: 081ed5f0-1bdf-406a-a2c5-b4f7341bf3ee
          is-owner: true
        display:
          success: Added Nox.Cli to the devops channel
          error: Unable to add Nox.Cli to the devops channel (${{ steps.add-cli-to-devops-channel.error-message }})
        run-at-server: true

      - name: Add DevOps group to devops channel
        id: add-devops-to-devops-channel
        uses: teams/add-channel-member@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          channel-id: ${{ steps.create-devops-channel.outputs.channel-id }}
          object-id: e00e4ac2-4318-472b-8c78-8cd8c3a54685
        display:
          success: Added DevOps to DevOps channel
          error: Unable to add DevOps to DevOps channel (${{ steps.add-devops-to-devops-channel.error-message }})
        run-at-server: true

      - name: Send Test message on DevOps channel
        id: send-devops-test-message
        uses: teams/send-channel-message@v1
        with:
          aad-client: ${{ steps.connect.outputs.aad-client }}
          team-id: ${{ steps.create-ms-team.outputs.team-id }}
          channel-id: ${{ steps.create-devops-channel.outputs.channel-id }}
          message-body: Welcome to the ${{ project.name }} DevOps team!
        display:
          success: Sent a test message to the devops team channel
          error: Unable to send a test message to the devops team channel (${{ steps.send-devops-test-message.error-message }})
        run-at-server: true

