//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nox.Cli.Validation {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nox.Cli.Validation.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AuthProviderEmpty {
            get {
                return ResourceManager.GetString("AuthProviderEmpty", resourceCulture);
            }
        }
        
        internal static string AuthProviderInvalid {
            get {
                return ResourceManager.GetString("AuthProviderInvalid", resourceCulture);
            }
        }
        
        internal static string AuthAuthorityEmpty {
            get {
                return ResourceManager.GetString("AuthAuthorityEmpty", resourceCulture);
            }
        }
        
        internal static string RteUrlEmpty {
            get {
                return ResourceManager.GetString("RteUrlEmpty", resourceCulture);
            }
        }
        
        internal static string RteApplicationIdEmpty {
            get {
                return ResourceManager.GetString("RteApplicationIdEmpty", resourceCulture);
            }
        }
    }
}
