<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nox.Cli.Abstractions\Nox.Cli.Abstractions.csproj" />
      <ProjectReference Include="..\Nox.Cli.Configuration\Nox.Cli.Configuration.csproj" />
      <ProjectReference Include="..\Nox.Cli.Helpers\Nox.Cli.Helpers.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Identity" Version="1.17.1" />
      <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" Version="10.0.3" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="Nox.Secrets.Azure" Version="8.0.17" />
      <PackageReference Include="Nox.Yaml" Version="8.0.17" />
      <PackageReference Include="RestSharp" Version="113.1.0" />
      <PackageReference Include="Spectre.Console" Version="0.54.0" />
    </ItemGroup>

</Project>
