name: Publish Workflows

on:
  push:
    branches: [ main ]
    paths:
      - .nox/workflows/**
      - .github/workflows/nox_workflows_publish.yaml

jobs:
  workflows-deploy:
    name: Deploy Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: Sync files with server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: .nox/workflows/          